CREATE TABLE categories
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted          BOOLEAN DEFAULT FALSE                   NOT NULL,
    note             TEXT    DEFAULT ''                      NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(255)                            NOT NULL,
    last_modified_by VARCHAR(255),
    version          BIGINT                                  NOT NULL,
    type_name        VARCHAR(50)                             NOT NULL,
    category_parent  BIGINT,
    image_id         VARCHAR(100),
    description      TEXT    DEFAULT '',
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_type_name UNIQUE (type_name);

ALTER TABLE categories
    ADD CONSTRAINT FK_CATEGORIES_ON_CATEGORY_PARENT FOREIGN KEY (category_parent) REFERENCES categories (id);