CREATE TABLE categories
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted          BOOLEAN DEFAULT FALSE                   NOT NULL,
    note             TEXT    DEFAULT ''                      NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(255)                            NOT NULL,
    last_modified_by VARCHAR(255),
    version          BIGINT                                  NOT NULL,
    type_name        VARCHAR(50)                             NOT NULL,
    category_parent  BIGINT,
    image_id         VARCHAR(100),
    description      TEXT    DEFAULT '',
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE foods
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted          BOOLEAN DEFAULT FALSE                   NOT NULL,
    note             TEXT    DEFAULT ''                      NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(255)                            NOT NULL,
    last_modified_by VARCHAR(255),
    version          BIGINT                                  NOT NULL,
    product_name     VARCHAR(100)                            NOT NULL,
    product_code     VARCHAR(50)                             NOT NULL,
    description      TEXT    DEFAULT '',
    brand            VARCHAR(200)                            NOT NULL,
    category_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_foods PRIMARY KEY (id)
);

CREATE TABLE product_attributes
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted          BOOLEAN DEFAULT FALSE                   NOT NULL,
    note             TEXT    DEFAULT ''                      NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(255)                            NOT NULL,
    last_modified_by VARCHAR(255),
    version          BIGINT                                  NOT NULL,
    attribute_name   VARCHAR(50)                             NOT NULL,
    description      TEXT    DEFAULT '',
    CONSTRAINT pk_product_attributes PRIMARY KEY (id)
);

CREATE TABLE product_images
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted          BOOLEAN DEFAULT FALSE                   NOT NULL,
    note             TEXT    DEFAULT ''                      NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(255)                            NOT NULL,
    last_modified_by VARCHAR(255),
    version          BIGINT                                  NOT NULL,
    product_id       BIGINT                                  NOT NULL,
    image_id         VARCHAR(100),
    display_main     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_product_images PRIMARY KEY (id)
);

CREATE TABLE product_prices
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted          BOOLEAN DEFAULT FALSE                   NOT NULL,
    note             TEXT    DEFAULT ''                      NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(255)                            NOT NULL,
    last_modified_by VARCHAR(255),
    version          BIGINT                                  NOT NULL,
    product_sku_id   BIGINT                                  NOT NULL,
    price_date       date                                    NOT NULL,
    price            DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_product_prices PRIMARY KEY (id)
);

CREATE TABLE product_sku_details
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted              BOOLEAN DEFAULT FALSE                   NOT NULL,
    note                 TEXT    DEFAULT ''                      NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_at     TIMESTAMP WITHOUT TIME ZONE,
    created_by           VARCHAR(255)                            NOT NULL,
    last_modified_by     VARCHAR(255),
    version              BIGINT                                  NOT NULL,
    product_sku_id       BIGINT                                  NOT NULL,
    product_attribute_id BIGINT                                  NOT NULL,
    value                TEXT    DEFAULT ''                      NOT NULL,
    CONSTRAINT pk_product_sku_details PRIMARY KEY (id)
);

CREATE TABLE product_skus
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted          BOOLEAN      DEFAULT FALSE              NOT NULL,
    note             TEXT         DEFAULT ''                 NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(255)                            NOT NULL,
    last_modified_by VARCHAR(255),
    version          BIGINT                                  NOT NULL,
    product_id       BIGINT                                  NOT NULL,
    sku_code         VARCHAR(50)                             NOT NULL,
    bar_code         VARCHAR(100),
    description      TEXT         DEFAULT '',
    manufacture_date date                                    NOT NULL,
    expire_date      date,
    status           VARCHAR(150) DEFAULT 'OUT_OF_STOCK'     NOT NULL,
    CONSTRAINT pk_product_skus PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_type_name UNIQUE (type_name);

ALTER TABLE foods
    ADD CONSTRAINT uc_foods_product_code UNIQUE (product_code);

ALTER TABLE product_attributes
    ADD CONSTRAINT uc_product_attributes_attribute_name UNIQUE (attribute_name);

ALTER TABLE product_images
    ADD CONSTRAINT uc_product_images_image UNIQUE (image_id);

ALTER TABLE product_skus
    ADD CONSTRAINT uc_product_skus_bar_code UNIQUE (bar_code);

ALTER TABLE product_skus
    ADD CONSTRAINT uc_product_skus_sku_code UNIQUE (sku_code);

ALTER TABLE categories
    ADD CONSTRAINT FK_CATEGORIES_ON_CATEGORY_PARENT FOREIGN KEY (category_parent) REFERENCES categories (id);

ALTER TABLE foods
    ADD CONSTRAINT FK_FOODS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE product_images
    ADD CONSTRAINT FK_PRODUCT_IMAGES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES foods (id);

ALTER TABLE product_prices
    ADD CONSTRAINT FK_PRODUCT_PRICES_ON_PRODUCT_SKU FOREIGN KEY (product_sku_id) REFERENCES product_skus (id);

ALTER TABLE product_skus
    ADD CONSTRAINT FK_PRODUCT_SKUS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES foods (id);

ALTER TABLE product_sku_details
    ADD CONSTRAINT FK_PRODUCT_SKU_DETAILS_ON_PRODUCT_ATTRIBUTE FOREIGN KEY (product_attribute_id) REFERENCES product_attributes (id);

ALTER TABLE product_sku_details
    ADD CONSTRAINT FK_PRODUCT_SKU_DETAILS_ON_PRODUCT_SKU FOREIGN KEY (product_sku_id) REFERENCES product_skus (id);